spring.application.name=ecommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true;

gemini.api.key=AIzaSyCwEgvgr9WZ487SGERyPNFxoy_2ZIBWY3A

# JWT Configuration
jwt.secret=dGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNg==
jwt.expiration=86400000

# === Ödeme Sistemi Ayarları ===

# Stripe Ayarları
stripe.api.key=sk_test_51TLmXwFenUoMJgzKNwUVD2hY4iNlU7vQZY7uqeFZbZ9r3CmiSPUVHrqoqGjNRdA7rFQGmSnbKgA0PqLSNK6jvjqZ00u9xJZIcO
stripe.webhook.secret=whsec_fa67f3ba360f4efcfef1cf638eeb609ad3272ba9cc0d721ff2ed3a23966b7678

# PayPal Sandbox Ayarları
paypal.client.id=YOUR_PAYPAL_CLIENT_ID
paypal.client.secret=YOUR_PAYPAL_SECRET
paypal.mode=sandbox

# Coinbase Commerce Ayarları
coinbase.api.key=yjXcq5JhwAEooz1XqBwmLb+m5bPRYrdaCuGHffEncG2eiOB26WrHJG3tTlhSDo5JpQUH37XYWPI9bajzCrTDhA==

# Kapıda Ödeme Ayarları
cod.max.amount=500.00
