package com.shop.ecommerce.enums;

public enum AuditAction {
    USER_LOGIN,
    USER_REGISTER,
    USER_SUSPENDED,
    USER_ACTIVATED,
    USER_DELETED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    ORDER_CREATED,
    ORDER_STATUS_UPDATED,
    STORE_OPENED,
    STORE_CLOSED,
    PAYMENT_PROCESSED,
    SHIPMENT_UPDATED
}
